% Clusters the images in the eth-80 dataset

addpath ../common/
clear all;
close all;

% Define the following constants
NUM_SIFT_DIMS = 128;
NUM_PCA_DIMS = 5;
SC_BANDWIDTH = 0.01; % bandwidth for spectral clustering

num_train_images_per_cluster = 100;
num_test_images_per_cluster = 10;

% categories = {'apples', ...
% %               'cars', ...
%               'cows', ...
%               'cups', ...
% %               'dogs', ...
% %               'pears', ...
% %               'tomatoes', ...
%               'horses'};
% categories = {'apples', ...
%               'cars', ...
%               'cows', ...
%               'cups', ...
%               'horses'};
categories = {'apples', ...
              'cows', ...
              'horses'};

% Obtain the Data
num_categories = numel(categories);
prepData;

% Compute distance matrix
% D = computeL2DistanceMatrix(data);

% Cluster and report results
fprintf('Clustering the Data\n');
[pred_labels, A] = distributionClustering(train_data, num_categories, ...
                                          SC_BANDWIDTH);

% Compute accuracy
fprintf('Avg_diag of confusion matrix: %f\n', ...
  confusion_matrix(pred_labels, train_labels));

